{% set name = "rabbitmq-delayed-message-exchange" %}
{% set version = "3.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/{{ version }}/rabbitmq_delayed_message_exchange-{{ version }}.ez
  sha256: 48dbe32dc64db9ac259b7e052b1565310935a83e3a74f154eb0c28baecdb15e3

build:
  number: 0
  skip: true  # [win]
  script: mkdir -p ${PREFIX}/lib/rabbitmq/plugins && cp *.ez ${PREFIX}/lib/rabbitmq/plugins

requirements:
  build:
  run:
    - rabbitmq-server >=3.8.16

test:
  commands:
    - rabbitmq-plugins list | grep rabbitmq_delayed_message_exchange

about:
  home: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE-MPL-RabbitMQ
  summary: Delayed Messaging for RabbitMQ
  description: |
    This plugin adds delayed-messaging (or scheduled-messaging) to RabbitMQ.

    A user can declare an exchange with the type x-delayed-message and
    then publish messages with the custom header x-delay expressing in
    milliseconds a delay time for the message. The message will be
    delivered to the respective queues after x-delay milliseconds.
  dev_url: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange

extra:
  recipe-maintainers:
    - anthchirp
    - ndevenish
