{% set name = "rabbitmq-delayed-message-exchange" %}
{% set version = "3.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/{{ version }}/rabbitmq_delayed_message_exchange-{{ version }}.ez
  sha256: 84d75c95b2cb0905e883fc4a8ce262533ff686e9ad13e8e1969aa4dab1c068d0

build:
  number: 0
  skip: true  # [win]
  script: mkdir -p ${PREFIX}/lib/rabbitmq/plugins && cp *.ez ${PREFIX}/lib/rabbitmq/plugins

requirements:
  build:
  run:
    - rabbitmq-server >=3.11.0

test:
  commands:
    - rabbitmq-plugins list | grep rabbitmq_delayed_message_exchange

about:
  home: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE-MPL-RabbitMQ
  summary: Delayed Messaging for RabbitMQ
  description: |
    This plugin adds delayed-messaging (or scheduled-messaging) to RabbitMQ.

    A user can declare an exchange with the type x-delayed-message and
    then publish messages with the custom header x-delay expressing in
    milliseconds a delay time for the message. The message will be
    delivered to the respective queues after x-delay milliseconds.
  dev_url: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange

extra:
  recipe-maintainers:
    - anthchirp
    - ndevenish
