{% set name = "rabbitmq-delayed-message-exchange" %}
{% set version = "3.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v{{ version }}/rabbitmq_delayed_message_exchange-{{ version }}.ez
  sha256: 3479180df03fa830fd59ccf638a60eee8f0e8261524a8616685522d7b8d9a9ee

build:
  number: 0
  skip: true  # [win]
  script: mkdir -p ${PREFIX}/lib/rabbitmq/plugins && cp *.ez ${PREFIX}/lib/rabbitmq/plugins

requirements:
  build:
  run:
    - rabbitmq-server >=3.13.0,<3.14

test:
  commands:
    - rabbitmq-plugins list | grep rabbitmq_delayed_message_exchange

about:
  home: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE-MPL-RabbitMQ
  summary: Delayed Messaging for RabbitMQ
  description: |
    This plugin adds delayed-messaging (or scheduled-messaging) to RabbitMQ.

    A user can declare an exchange with the type x-delayed-message and
    then publish messages with the custom header x-delay expressing in
    milliseconds a delay time for the message. The message will be
    delivered to the respective queues after x-delay milliseconds.
  dev_url: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange

extra:
  recipe-maintainers:
    - anthchirp
    - ndevenish
