{% set name = "rabbitmq-delayed-message-exchange" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v{{ version }}/rabbitmq_delayed_message_exchange-{{ version }}.ez
  sha256: eea05bc9f56761252199698c6115cc703a2d373f7c7e1642add0f799b35166a4

build:
  number: 0
  skip: true  # [win]
  script: mkdir -p ${PREFIX}/lib/rabbitmq/plugins && cp *.ez ${PREFIX}/lib/rabbitmq/plugins

requirements:
  build:
  run:
    - rabbitmq-server >=4.0.2,<4.1

test:
  commands:
    - rabbitmq-plugins list | grep rabbitmq_delayed_message_exchange

about:
  home: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE-MPL-RabbitMQ
  summary: Delayed Messaging for RabbitMQ
  description: |
    This plugin adds delayed-messaging (or scheduled-messaging) to RabbitMQ.

    A user can declare an exchange with the type x-delayed-message and
    then publish messages with the custom header x-delay expressing in
    milliseconds a delay time for the message. The message will be
    delivered to the respective queues after x-delay milliseconds.
  dev_url: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange

extra:
  recipe-maintainers:
    - anthchirp
    - ndevenish
