{% set name = "rabbitmq-delayed-message-exchange" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v{{ version }}/rabbitmq_delayed_message_exchange-{{ version }}.ez
  sha256: 567f876378e70af9d949de4066bbb2fc30162b46bcbc9efe2430076b172e4a87

build:
  number: 0
  skip: true  # [win]
  script: mkdir -p ${PREFIX}/lib/rabbitmq/plugins && cp *.ez ${PREFIX}/lib/rabbitmq/plugins

requirements:
  build:
  run:
    - rabbitmq-server >=4.1.0,<4.2

test:
  commands:
    - rabbitmq-plugins list | grep rabbitmq_delayed_message_exchange

about:
  home: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE-MPL-RabbitMQ
  summary: Delayed Messaging for RabbitMQ
  description: |
    This plugin adds delayed-messaging (or scheduled-messaging) to RabbitMQ.

    A user can declare an exchange with the type x-delayed-message and
    then publish messages with the custom header x-delay expressing in
    milliseconds a delay time for the message. The message will be
    delivered to the respective queues after x-delay milliseconds.
  dev_url: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange

extra:
  recipe-maintainers:
    - anthchirp
    - ndevenish
